# Game config for AURAGAMING - WWE - 2K25 AURA EDITION by
[General]
Enable Logging = True
FileLogging = False
ForceLagSync2 = False
AutoLoadSaveState = 0
EnableCheats = True
EnablePlugins = True
CwCheatRefreshRate = 77
CwCheatScrollPosition = 0.000000
DisableHLEFlags = 0
ForceEnableHLEFlags = 0
ScreenshotsAsPNG = False
StateSlot = 4
EnableStateUndo = False
RewindSnapshotInterval = 0
RightAnalogUp = 0
RightAnalogDown = 0
RightAnalogLeft = 0
RightAnalogRight = 0
RightAnalogPress = 0
RightAnalogCustom = False
RightAnalogDisableDiagonal = False
SwipeUp = 0
SwipeDown = 0
SwipeLeft = 0
SwipeRight = 0
SwipeSensitivity = 1.000000
SwipeSmoothing = 0.300000
DoubleTapGesture = 0
GestureControlEnabled = False
TouchGliding = False
AutoSaveSymbolMap = False
CacheFullIsoInRam = False
AskForExitConfirmationAfterSeconds = 60
InternalScreenRotation = 1
PauseWhenMinimized = False
DumpFileTypes = 0
MemStickInserted = True
LoadPlugins = True
IgnoreCompatSettings = 
ShowGPOLEDs = False
[CPU]
CPUCore = 1
SeparateSASThread = True
IOTimingMethod = 0
FastMemoryAccess = True
FunctionReplacements = True
JitDisableFlags = 0x00000000
CPUSpeed = 0
[Graphics]
EnableCardboardVR = False
CardboardScreenSize = 50
CardboardXShift = 0
CardboardYShift = 0
iShowStatusFlags = 0
UseGeometryShader = False
SkipBufferEffects = False
DisableRangeCulling = False
DepthRasterMode = 1
SoftwareRenderer = False
SoftwareRendererJit = True
HardwareTransform = True
SoftwareSkinning = True
TextureFiltering = 1
Smart2DTexFiltering = False
InternalResolution = 3
HighQualityDepth = 1
FrameSkip = 2
FrameSkipType = 0
AutoFrameSkip = True
StereoRendering = False
StereoToMonoShader = RedBlue
FrameRate = 600
FrameRate2 = 600
AnalogFrameRate = 240
UnthrottlingMode = SKIP_FLIP
AnisotropyLevel = 2
MultiSampleLevel = 0
TextureBackoffCache = True
BufferFiltering = 1
DisplayOffsetX = 0.500000
DisplayOffsetY = 0.500000
DisplayScale = 1.000000
DisplayIntegerScale = False
DisplayAspectRatio = 1.000000
DisplayStretch = False
DisplayCropTo16x9 = True
ImmersiveMode = False
SustainedPerformanceMode = False
ReplaceTextures = True
SaveNewTextures = False
IgnoreTextureFilenames = False
ReplacementTextureLoadSpeed = 0
TexScalingLevel = 1
TexScalingType = 0
TexDeposterize = False
TexHardwareScaling = False
VSync = True
BloomHack = 0
SplineBezierQuality = 0
HardwareTessellation = False
TextureShader = Off
ShaderChainRequires60FPS = False
SkipGPUReadbackMode = 0
RenderDuplicateFrames = False
DisplayRefreshRate = 60
VerticalSync = True
LowLatencyPresent = False
[Sound]
Enable = True
AudioBackend = 0
GameVolume = 100
ReverbRelativeVolume = 100
AltSpeedRelativeVolume = 100
AchievementVolume = 75
[Control]
HapticFeedback = False
ShowTouchCross = True
ShowTouchCircle = True
ShowTouchSquare = True
ShowTouchTriangle = True
Custom0Mapping = 0x0000000000000000
Custom0Image = 0
Custom0Shape = 0
Custom0Toggle = False
Custom0Repeat = False
Custom1Mapping = 0x0000000000000000
Custom1Image = 1
Custom1Shape = 0
Custom1Toggle = False
Custom1Repeat = False
Custom2Mapping = 0x0000000000000000
Custom2Image = 2
Custom2Shape = 0
Custom2Toggle = False
Custom2Repeat = False
Custom3Mapping = 0x0000000000000000
Custom3Image = 3
Custom3Shape = 0
Custom3Toggle = False
Custom3Repeat = False
Custom4Mapping = 0x0000000000000000
Custom4Image = 4
Custom4Shape = 0
Custom4Toggle = False
Custom4Repeat = False
Custom5Mapping = 0x0000000000000000
Custom5Image = 0
Custom5Shape = 1
Custom5Toggle = False
Custom5Repeat = False
Custom6Mapping = 0x0000000000000000
Custom6Image = 1
Custom6Shape = 1
Custom6Toggle = False
Custom6Repeat = False
Custom7Mapping = 0x0000000000000000
Custom7Image = 2
Custom7Shape = 1
Custom7Toggle = False
Custom7Repeat = False
Custom8Mapping = 0x0000000000000000
Custom8Image = 3
Custom8Shape = 1
Custom8Toggle = False
Custom8Repeat = False
Custom9Mapping = 0x0000000000000000
Custom9Image = 4
Custom9Shape = 1
Custom9Toggle = False
Custom9Repeat = False
Custom10Mapping = 0x0000000000000000
Custom10Image = 0
Custom10Shape = 2
Custom10Toggle = False
Custom10Repeat = False
Custom11Mapping = 0x0000000000000000
Custom11Image = 1
Custom11Shape = 2
Custom11Toggle = False
Custom11Repeat = False
Custom12Mapping = 0x0000000000000000
Custom12Image = 2
Custom12Shape = 2
Custom12Toggle = False
Custom12Repeat = False
Custom13Mapping = 0x0000000000000000
Custom13Image = 3
Custom13Shape = 2
Custom13Toggle = False
Custom13Repeat = False
Custom14Mapping = 0x0000000000000000
Custom14Image = 4
Custom14Shape = 2
Custom14Toggle = False
Custom14Repeat = False
Custom15Mapping = 0x0000000000000000
Custom15Image = 0
Custom15Shape = 9
Custom15Toggle = False
Custom15Repeat = False
Custom16Mapping = 0x0000000000000000
Custom16Image = 1
Custom16Shape = 9
Custom16Toggle = False
Custom16Repeat = False
Custom17Mapping = 0x0000000000000000
Custom17Image = 2
Custom17Shape = 9
Custom17Toggle = False
Custom17Repeat = False
Custom18Mapping = 0x0000000000000000
Custom18Image = 3
Custom18Shape = 9
Custom18Toggle = False
Custom18Repeat = False
Custom19Mapping = 0x0000000000000000
Custom19Image = 4
Custom19Shape = 9
Custom19Toggle = False
Custom19Repeat = False
fcombo0X = 0.621359
fcombo0Y = 0.500000
comboKeyScale0 = 1.150000
ShowComboKey0 = False
fcombo1X = 0.722860
fcombo1Y = 0.500000
comboKeyScale1 = 1.150000
ShowComboKey1 = False
fcombo2X = 0.824360
fcombo2Y = 0.500000
comboKeyScale2 = 1.150000
ShowComboKey2 = False
fcombo3X = 0.621359
fcombo3Y = 0.333333
comboKeyScale3 = 1.150000
ShowComboKey3 = False
fcombo4X = 0.722860
fcombo4Y = 0.333333
comboKeyScale4 = 1.150000
ShowComboKey4 = False
fcombo5X = 0.399895
fcombo5Y = 0.500000
comboKeyScale5 = 1.150000
ShowComboKey5 = False
fcombo6X = 0.316884
fcombo6Y = 0.500000
comboKeyScale6 = 1.150000
ShowComboKey6 = False
fcombo7X = 0.233874
fcombo7Y = 0.500000
comboKeyScale7 = 1.150000
ShowComboKey7 = False
fcombo8X = 0.399895
fcombo8Y = 0.331804
comboKeyScale8 = 1.150000
ShowComboKey8 = False
fcombo9X = 0.316884
fcombo9Y = 0.331804
comboKeyScale9 = 1.150000
ShowComboKey9 = False
fcombo10X = 0.599121
fcombo10Y = 0.582569
comboKeyScale10 = 1.150000
ShowComboKey10 = False
fcombo11X = 0.682131
fcombo11Y = 0.582569
comboKeyScale11 = 1.150000
ShowComboKey11 = False
fcombo12X = 0.765142
fcombo12Y = 0.582569
comboKeyScale12 = 1.150000
ShowComboKey12 = False
fcombo13X = 0.599121
fcombo13Y = 0.415902
comboKeyScale13 = 1.150000
ShowComboKey13 = False
fcombo14X = 0.682131
fcombo14Y = 0.415902
comboKeyScale14 = 1.150000
ShowComboKey14 = False
fcombo15X = 0.399895
fcombo15Y = 0.582569
comboKeyScale15 = 1.150000
ShowComboKey15 = False
fcombo16X = 0.316884
fcombo16Y = 0.582569
comboKeyScale16 = 1.150000
ShowComboKey16 = False
fcombo17X = 0.233874
fcombo17Y = 0.582569
comboKeyScale17 = 1.150000
ShowComboKey17 = False
fcombo18X = 0.399895
fcombo18Y = 0.415902
comboKeyScale18 = 1.150000
ShowComboKey18 = False
fcombo19X = 0.316884
fcombo19Y = 0.415902
comboKeyScale19 = 1.150000
ShowComboKey19 = False
ShowTouchControls = True
TiltBaseAngleY = 0.900000
TiltInvertX = False
TiltInvertY = False
TiltSensitivityX = 100
TiltSensitivityY = 100
TiltAnalogDeadzoneRadius = 0.000000
TiltInverseDeadzone = 0.000000
TiltCircularDeadzone = True
TiltInputType = 0
DisableDpadDiagonals = False
GamepadOnlyFocused = False
TouchButtonStyle = 1
TouchButtonOpacity = 100
TouchButtonHideSeconds = 300
AutoCenterTouchAnalog = False
StickyTouchDPad = False
TouchSnapToGrid = False
TouchSnapGridSize = 64
ActionButtonSpacing2 = 1.000000
ActionButtonCenterX = 0.849462
ActionButtonCenterY = 0.718518
ActionButtonScale = 1.150000
DPadX = 0.126214
DPadY = 0.466667
DPadScale = 1.150000
ShowTouchDpad = True
DPadSpacing = 1.000000
StartKeyX = 0.601059
StartKeyY = 0.872222
StartKeyScale = 1.150000
ShowTouchStart = True
SelectKeyX = 0.499559
SelectKeyY = 0.872222
SelectKeyScale = 1.150000
ShowTouchSelect = True
UnthrottleKeyX = 0.398058
UnthrottleKeyY = 0.872222
UnthrottleKeyScale = 1.150000
ShowTouchUnthrottle = True
LKeyX = 0.060900
LKeyY = 0.190741
LKeyScale = 1.150000
ShowTouchLTrigger = True
RKeyX = 0.939100
RKeyY = 0.190741
RKeyScale = 1.150000
ShowTouchRTrigger = True
AnalogStickX = 0.126214
AnalogStickY = 0.829630
AnalogStickScale = 1.150000
ShowAnalogStick = True
RightAnalogStickX = 0.894086
RightAnalogStickY = 0.829630
RightAnalogStickScale = 1.150000
ShowRightAnalogStick = False
AnalogDeadzone = 0.150000
AnalogInverseDeadzone = 0.000000
AnalogSensitivity = 1.100000
AnalogIsCircular = False
AnalogAutoRotSpeed = 8.000000
LeftStickHeadScale = 1.000000
RightStickHeadScale = 1.000000
HideStickBackground = False
UseMouse = False
ConfineMap = False
MouseSensitivity = 0.100000
MouseSmoothing = 0.900000
MouseWheelUpDelayMs = 80
AnalogGesture = False
AnalogGestureSensibility = 1.000000
TiltInputEnabled = False
[SystemParam]
PSPModel = 0
PSPFirmwareVersion = 660
NickName = PPSSPP
MacAddress = 9b:1c:04:88:bc:cb
GameLanguage = -1
ParamTimeFormat = 0
ParamDateFormat = 0
TimeZone = 0
DayLightSavings = False
ButtonPreference = 1
LockParentalLevel = 0
WlanAdhocChannel = 0
BypassOSKWithKeyboard = False
WlanPowerSave = False
EncryptSave = False
[Network]
EnableWlan = False
EnableAdhocServer = False
proAdhocServer = socom.cc
PortOffset = 10000
PrimaryDNSServer = 67.222.156.250
MinTimeout = 0
ForcedFirstConnect = False
EnableUPnP = False
UPnPUseOriginalPort = False
InfrastructureUsername = 
InfrastructureAutoDNS = True
AllowSpeedControlWhileConnected = False
EnableNetworkChat = False
ChatButtonPosition = 0
ChatScreenPosition = 0
EnableQuickChat = True
QuickChat1 = Quick Chat 1
QuickChat2 = Quick Chat 2
QuickChat3 = Quick Chat 3
QuickChat4 = Quick Chat 4
QuickChat5 = Quick Chat 5
AdhocServerRelayMode = 0
AdhocServerShowPlayerPorts = False
[VR]
VREnable = True
VREnable6DoF = False
VREnableStereo = False
VRForce72Hz = True
VRImmersiveMode = True
VRManualForceVR = False
VRPassthrough = False
VRRescaleHUD = True
VRCameraDistance = 0.000000
VRCameraHeight = 0.000000
VRCameraSide = 0.000000
VRCameraPitch = 0.000000
VRFieldOfView = 100.000000
VRHeadUpDisplayScale = 0.300000
[Achievements]
AchievementsChallengeMode = True
AchievementsEncoreMode = False
AchievementsUnofficial = False
AchievementsLeaderboardTrackerPos = 3
AchievementsLeaderboardStartedOrFailedPos = 3
AchievementsLeaderboardSubmittedPos = 3
AchievementsProgressPos = 3
AchievementsChallengePos = 3
AchievementsUnlockedPos = 4
AchievementsEnable = False
[ControlMapping]
Up = 10-4033
Down = 10-4032
Left = 10-4031
Right = 10-4030
Circle = 10-97
Cross = 10-96
Square = 10-99
Triangle = 10-100
Start = 10-108
Select = 10-109
L = 10-102
R = 10-103
An.Up = 10-4003
An.Down = 10-4002
An.Left = 10-4001
An.Right = 10-4000
Pause = 10-1
SpeedToggle = 10-104
[DisplayLayout.Landscape]
BufferFiltering = 1
DisplayStretch = True
DisplayOffsetX = 0.502742
DisplayOffsetY = 0.474048
DisplayScale = 1.139973
DisplayIntegerScale = False
DisplayAspectRatio = 1.000000
IgnoreScreenInsets = False
InternalScreenRotation = 1
RotateControlsWithScreen = True
EnableCardboardVR = False
CardboardScreenSize = 50
CardboardXShift = 0
CardboardYShift = 0
ImmersiveMode = False
[DisplayLayout.Portrait]
BufferFiltering = 1
DisplayStretch = False
DisplayOffsetX = 0.500000
DisplayOffsetY = 0.250000
DisplayScale = 1.000000
DisplayIntegerScale = False
DisplayAspectRatio = 1.000000
IgnoreScreenInsets = True
InternalScreenRotation = 1
RotateControlsWithScreen = True
EnableCardboardVR = False
CardboardScreenSize = 50
CardboardXShift = 0
CardboardYShift = 0
ImmersiveMode = False
[TouchControls.Landscape]
ShowTouchCross = True
ShowTouchCircle = True
ShowTouchSquare = True
ShowTouchTriangle = True
fcombo0X = 0.621359
fcombo0Y = 0.500000
comboKeyScale0 = 1.150000
ShowComboKey0 = False
fcombo1X = 0.722860
fcombo1Y = 0.500000
comboKeyScale1 = 1.150000
ShowComboKey1 = False
fcombo2X = 0.824360
fcombo2Y = 0.500000
comboKeyScale2 = 1.150000
ShowComboKey2 = False
fcombo3X = 0.621359
fcombo3Y = 0.333333
comboKeyScale3 = 1.150000
ShowComboKey3 = False
fcombo4X = 0.722860
fcombo4Y = 0.333333
comboKeyScale4 = 1.150000
ShowComboKey4 = False
fcombo5X = 0.399895
fcombo5Y = 0.500000
comboKeyScale5 = 1.150000
ShowComboKey5 = False
fcombo6X = 0.316884
fcombo6Y = 0.500000
comboKeyScale6 = 1.150000
ShowComboKey6 = False
fcombo7X = 0.233874
fcombo7Y = 0.500000
comboKeyScale7 = 1.150000
ShowComboKey7 = False
fcombo8X = 0.399895
fcombo8Y = 0.331804
comboKeyScale8 = 1.150000
ShowComboKey8 = False
fcombo9X = 0.316884
fcombo9Y = 0.331804
comboKeyScale9 = 1.150000
ShowComboKey9 = False
fcombo10X = 0.599121
fcombo10Y = 0.582569
comboKeyScale10 = 1.150000
ShowComboKey10 = False
fcombo11X = 0.682131
fcombo11Y = 0.582569
comboKeyScale11 = 1.150000
ShowComboKey11 = False
fcombo12X = 0.765142
fcombo12Y = 0.582569
comboKeyScale12 = 1.150000
ShowComboKey12 = False
fcombo13X = 0.599121
fcombo13Y = 0.415902
comboKeyScale13 = 1.150000
ShowComboKey13 = False
fcombo14X = 0.682131
fcombo14Y = 0.415902
comboKeyScale14 = 1.150000
ShowComboKey14 = False
fcombo15X = 0.399895
fcombo15Y = 0.582569
comboKeyScale15 = 1.150000
ShowComboKey15 = False
fcombo16X = 0.316884
fcombo16Y = 0.582569
comboKeyScale16 = 1.150000
ShowComboKey16 = False
fcombo17X = 0.233874
fcombo17Y = 0.582569
comboKeyScale17 = 1.150000
ShowComboKey17 = False
fcombo18X = 0.399895
fcombo18Y = 0.415902
comboKeyScale18 = 1.150000
ShowComboKey18 = False
fcombo19X = 0.316884
fcombo19Y = 0.415902
comboKeyScale19 = 1.150000
ShowComboKey19 = False
ActionButtonSpacing2 = 1.000000
ActionButtonCenterX = 0.849462
ActionButtonCenterY = 0.718518
ActionButtonScale = 1.150000
DPadX = 0.126214
DPadY = 0.466667
DPadScale = 1.150000
ShowTouchDpad = True
DPadSpacing = 1.000000
StartKeyX = 0.601059
StartKeyY = 0.872222
StartKeyScale = 1.150000
ShowTouchStart = True
SelectKeyX = 0.499559
SelectKeyY = 0.872222
SelectKeyScale = 1.150000
ShowTouchSelect = True
UnthrottleKeyX = 0.398058
UnthrottleKeyY = 0.872222
UnthrottleKeyScale = 1.150000
ShowTouchUnthrottle = True
LKeyX = 0.060900
LKeyY = 0.190741
LKeyScale = 1.150000
ShowTouchLTrigger = True
RKeyX = 0.939100
RKeyY = 0.190741
RKeyScale = 1.150000
ShowTouchRTrigger = True
PauseKeyX = 0.499923
PauseKeyY = 0.040698
PauseKeyScale = 0.920000
ShowTouchPause = True
AnalogStickX = 0.126214
AnalogStickY = 0.829630
AnalogStickScale = 1.150000
ShowAnalogStick = True
RightAnalogStickX = 0.894086
RightAnalogStickY = 0.829630
RightAnalogStickScale = 1.150000
ShowRightAnalogStick = False
LeftStickHeadScale = 1.000000
RightStickHeadScale = 1.000000
HideStickBackground = False
[TouchControls.Portrait]
ShowTouchCross = True
ShowTouchCircle = True
ShowTouchSquare = True
ShowTouchTriangle = True
fcombo0X = -1.000000
fcombo0Y = -1.000000
comboKeyScale0 = 1.150000
ShowComboKey0 = False
fcombo1X = -1.000000
fcombo1Y = -1.000000
comboKeyScale1 = 1.150000
ShowComboKey1 = False
fcombo2X = -1.000000
fcombo2Y = -1.000000
comboKeyScale2 = 1.150000
ShowComboKey2 = False
fcombo3X = -1.000000
fcombo3Y = -1.000000
comboKeyScale3 = 1.150000
ShowComboKey3 = False
fcombo4X = -1.000000
fcombo4Y = -1.000000
comboKeyScale4 = 1.150000
ShowComboKey4 = False
fcombo5X = -1.000000
fcombo5Y = -1.000000
comboKeyScale5 = 1.150000
ShowComboKey5 = False
fcombo6X = -1.000000
fcombo6Y = -1.000000
comboKeyScale6 = 1.150000
ShowComboKey6 = False
fcombo7X = -1.000000
fcombo7Y = -1.000000
comboKeyScale7 = 1.150000
ShowComboKey7 = False
fcombo8X = -1.000000
fcombo8Y = -1.000000
comboKeyScale8 = 1.150000
ShowComboKey8 = False
fcombo9X = -1.000000
fcombo9Y = -1.000000
comboKeyScale9 = 1.150000
ShowComboKey9 = False
fcombo10X = -1.000000
fcombo10Y = -1.000000
comboKeyScale10 = 1.150000
ShowComboKey10 = False
fcombo11X = -1.000000
fcombo11Y = -1.000000
comboKeyScale11 = 1.150000
ShowComboKey11 = False
fcombo12X = -1.000000
fcombo12Y = -1.000000
comboKeyScale12 = 1.150000
ShowComboKey12 = False
fcombo13X = -1.000000
fcombo13Y = -1.000000
comboKeyScale13 = 1.150000
ShowComboKey13 = False
fcombo14X = -1.000000
fcombo14Y = -1.000000
comboKeyScale14 = 1.150000
ShowComboKey14 = False
fcombo15X = -1.000000
fcombo15Y = -1.000000
comboKeyScale15 = 1.150000
ShowComboKey15 = False
fcombo16X = -1.000000
fcombo16Y = -1.000000
comboKeyScale16 = 1.150000
ShowComboKey16 = False
fcombo17X = -1.000000
fcombo17Y = -1.000000
comboKeyScale17 = 1.150000
ShowComboKey17 = False
fcombo18X = -1.000000
fcombo18Y = -1.000000
comboKeyScale18 = 1.150000
ShowComboKey18 = False
fcombo19X = -1.000000
fcombo19Y = -1.000000
comboKeyScale19 = 1.150000
ShowComboKey19 = False
ActionButtonSpacing2 = 1.000000
ActionButtonCenterX = -1.000000
ActionButtonCenterY = -1.000000
ActionButtonScale = 1.150000
DPadX = -1.000000
DPadY = -1.000000
DPadScale = 1.150000
ShowTouchDpad = True
DPadSpacing = 1.000000
StartKeyX = -1.000000
StartKeyY = -1.000000
StartKeyScale = 1.150000
ShowTouchStart = True
SelectKeyX = -1.000000
SelectKeyY = -1.000000
SelectKeyScale = 1.150000
ShowTouchSelect = True
UnthrottleKeyX = -1.000000
UnthrottleKeyY = -1.000000
UnthrottleKeyScale = 1.150000
ShowTouchUnthrottle = True
LKeyX = -1.000000
LKeyY = -1.000000
LKeyScale = 1.150000
ShowTouchLTrigger = True
RKeyX = -1.000000
RKeyY = -1.000000
RKeyScale = 1.150000
ShowTouchRTrigger = True
PauseKeyX = -1.000000
PauseKeyY = -1.000000
PauseKeyScale = 1.150000
ShowTouchPause = True
AnalogStickX = -1.000000
AnalogStickY = -1.000000
AnalogStickScale = 1.150000
ShowAnalogStick = True
RightAnalogStickX = -1.000000
RightAnalogStickY = -1.000000
RightAnalogStickScale = 1.150000
ShowRightAnalogStick = False
LeftStickHeadScale = 1.000000
RightStickHeadScale = 1.000000
HideStickBackground = False
[GestureControls.Left]
SwipeUp = 0
SwipeDown = 0
SwipeLeft = 0
SwipeRight = 0
SwipeSensitivity = 1.000000
SwipeSmoothing = 0.300000
DoubleTapGesture = 0
GestureControlEnabled = False
AnalogGesture = False
AnalogGestureSensibility = 1.000000
[GestureControls.Right]
SwipeUp = 0
SwipeDown = 0
SwipeLeft = 0
SwipeRight = 0
SwipeSensitivity = 1.000000
SwipeSmoothing = 0.300000
DoubleTapGesture = 0
GestureControlEnabled = False
AnalogGesture = False
AnalogGestureSensibility = 1.000000
